language: python
python:
  - "3.6"
install:
  - pip3 -q install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
  - pip3 install torchvision
  - pip3 install -r requirements.txt
script:
  - python -m unittest -v
